from scipy import *
from pylab import *
path1='../files/Sz_files/Sz.dat'
path2='../files/Sz_files/Sz=0.dat'
path3='../files/Sz_files/Sz=1.0.dat'
path4='../files/Sz_files/Sz=2.0.dat'
path5='../files/Sz_files/Sz=0.5.dat'
path6='../files/Sz_files/Sz=1.5.dat'

dat1=loadtxt(path1).transpose()
dat2=loadtxt(path2).transpose()
dat3=loadtxt(path3).transpose()
dat4=loadtxt(path4).transpose()
dat5=loadtxt(path5).transpose()
dat6=loadtxt(path6).transpose()
T=11600.0/dat1[0][1:]
print T
a1=dat1[1][1:]
a2=dat1[2][1:]
a3=dat1[3][1:]
a4=dat1[4][1:]
grid()
xlim([0,1200])
xlabel("T(K)-->",fontsize=25)
ylabel("|$S_{z}$|-->",fontsize=25)
plot(T,a1,'ro-',label="$HTa^-$")
plot(T,a2,'bo-',label="$LTa^-$")
plot(T,a3,'yo-',label="$HTa^0$")
plot(T,a4,'go-',label="$LTa^0$")
ax=gca()
for label in ax.get_xticklabels()+ax.get_yticklabels():
	label.set_fontsize(16)
legend(loc=0)
savefig("../output/Sz.png")
show()
#a1=dat2[1][1:]
#a2=dat2[2][1:]
#a3=dat2[3][1:]
#a4=dat2[4][1:]
#xlim([0,1200])
#xlabel("T(K)-->",fontsize=20)
#ylabel("Probability-->",fontsize=20)
#plot(T,a1,'ro-',label="$HTa^-$")
#plot(T,a2,'bo-',label="$LTa^-$")
#plot(T,a3,'go-',label="$HTa^0$")
#plot(T,a4,'yo-',label="$LTa^0$")
#legend(loc=0)
#grid()
#savefig("../output/Sz=0.png")
#show()
#
#a1=dat3[1][1:]
#a2=dat3[2][1:]
#a3=dat3[3][1:]
#a4=dat3[4][1:]
#xlim([0,1200])
#xlabel("T(K)-->",fontsize=20)
#ylabel("Probability-->",fontsize=20)
#plot(T,a1,'ro-',label="$HTa^-$")
#plot(T,a2,'bo-',label="$LTa^-$")
#plot(T,a3,'go-',label="$HTa^0$")
#plot(T,a4,'yo-',label="$LTa^0$")
#legend(loc=0)
#grid()
#savefig("../output/Sz=1.png")
#show()
#a1=dat4[1][1:]
#a2=dat4[2][1:]
#a3=dat4[3][1:]
#a4=dat4[4][1:]
#xlim([0,1200])
#xlabel("T(K)-->",fontsize=20)
#ylabel("Probability-->",fontsize=20)
#plot(T,a1,'ro-',label="$HTa^-$")
#plot(T,a2,'bo-',label="$LTa^-$")
#plot(T,a3,'go-',label="$HTa^0$")
#plot(T,a4,'yo-',label="$LTa^0$")
#legend(loc=0)
#grid()
#savefig("../output/Sz=2.png")
#show()
#a1=dat5[1][1:]
#a2=dat5[2][1:]
#a3=dat5[3][1:]
#a4=dat5[4][1:]
#xlim([0,1200])
#xlabel("T(K)-->",fontsize=20)
#ylabel("Probability-->",fontsize=20)
#plot(T,a1,'ro-',label="$HTa^-$")
#plot(T,a2,'bo-',label="$LTa^-$")
#plot(T,a3,'go-',label="$HTa^0$")
#plot(T,a4,'yo-',label="$LTa^0$")
#legend(loc=0)
#grid()
#savefig("../output/Sz=0.5.png")
#show()
#a1=dat6[1][1:]
#a2=dat6[2][1:]
#a3=dat6[3][1:]
#a4=dat6[4][1:]
#xlim([0,1200])
#xlabel("T(K)-->",fontsize=20)
#ylabel("Probability-->",fontsize=20)
#plot(T,a1,'ro-',label="$HTa^-$")
#plot(T,a2,'bo-',label="$LTa^-$")
#plot(T,a3,'go-',label="$HTa^0$")
#plot(T,a4,'yo-',label="$LTa^0$")
#legend(loc=0)
#grid()
#savefig("../output/Sz=1.5.png")
#show()
a1=dat2[1][1:]
a2=dat3[1][1:]
a3=dat4[1][1:]
a4=dat5[1][1:]
a5=dat6[1][1:]
xlim([0,1200])
xlabel("T(K)-->",fontsize=25)
ylabel("Probability-->",fontsize=25)
plot(T,a1,'ro-',label="|Sz|=0")
plot(T,a4,'yo-',label="|Sz|=0.5")
plot(T,a2,'bo-',label="|Sz|=1.0")
plot(T,a5,'co-',label="|Sz|=1.5")
plot(T,a3,'go-',label="|Sz|=2.0")
ax=gca()
for label in ax.get_xticklabels()+ax.get_yticklabels():
	label.set_fontsize(16)
legend(loc=0)
grid()
savefig("../output/a-a-a-_ht_Sz.png")
show()
a1=dat2[2][1:]
a2=dat3[2][1:]
a3=dat4[2][1:]
a4=dat5[2][1:]
a5=dat6[2][1:]
xlim([0,1200])
xlabel("T(K)-->",fontsize=25)
ylabel("Probability-->",fontsize=25)
plot(T,a1,'ro-',label="|Sz|=0")
plot(T,a4,'yo-',label="|Sz|=0.5")
plot(T,a2,'bo-',label="|Sz|=1.0")
plot(T,a5,'co-',label="|Sz|=1.5")
plot(T,a3,'go-',label="|Sz|=2.0")
ax=gca()
for label in ax.get_xticklabels()+ax.get_yticklabels():
	label.set_fontsize(16)
legend(loc=0)
grid()
savefig("../output/a-a-a-_lt_Sz.png")
show()
a1=dat2[3][1:]
a2=dat3[3][1:]
a3=dat4[3][1:]
a4=dat5[3][1:]
a5=dat6[3][1:]
xlim([0,1200])
xlabel("T(K)-->",fontsize=25)
ylabel("Probability-->",fontsize=25)
plot(T,a1,'ro-',label="|Sz|=0")
plot(T,a4,'yo-',label="|Sz|=0.5")
plot(T,a2,'bo-',label="|Sz|=1.0")
plot(T,a5,'co-',label="|Sz|=1.5")
plot(T,a3,'go-',label="|Sz|=2.0")
ax=gca()
for label in ax.get_xticklabels()+ax.get_yticklabels():
	label.set_fontsize(16)
legend(loc=0)
grid()
savefig("../output/a0a0a0_ht_Sz.png")
show()
a1=dat2[4][1:]
a2=dat3[4][1:]
a3=dat4[4][1:]
a4=dat5[4][1:]
a5=dat6[4][1:]
xlim([0,1200])
xlabel("T(K)-->",fontsize=25)
ylabel("Probability-->",fontsize=25)
plot(T,a1,'ro-',label="|Sz|=0")
plot(T,a4,'yo-',label="|Sz|=0.5")
plot(T,a2,'bo-',label="|Sz|=1.0")
plot(T,a5,'co-',label="|Sz|=1.5")
plot(T,a3,'go-',label="|Sz|=2.0")
ax=gca()
for label in ax.get_xticklabels()+ax.get_yticklabels():
	label.set_fontsize(16)
legend(loc=0)
grid()
savefig("../output/a0a0a0_lt_Sz.png")
show()
